import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Mail, LockKeyhole, Eye, EyeOff, ArrowRight, LoaderCircle, CheckCircle2, AlertCircle, RotateCcw, LogOut } from 'lucide-react'
import { supabase, isSupabaseConfigured } from './supabase'
import './styles.css'
const BASE = '/DoULife'
const isValidEmail = (email) => /^\S+@\S+\.\S+$/.test(email.trim())

const thaiError = (message='') => {
  if (/invalid login credentials/i.test(message)) return 'อีเมลหรือรหัสผ่านไม่ถูกต้อง'
  if (/network|fetch/i.test(message)) return 'ไม่สามารถเชื่อมต่อได้ กรุณาตรวจสอบอินเทอร์เน็ต'
  return 'เกิดข้อผิดพลาด กรุณาลองใหม่อีกครั้ง'
}


function Logo(){ return <div className="brand"><div className="brand-mark">ก</div><div><b>เรียนภาษา</b><span>เรียนรู้ทุกวัน สนุกทุกคำ</span></div></div> }
function Mascot(){ return <div className="mascot-wrap" aria-hidden="true"><div className="sparkle s1">✦</div><div className="sparkle s2">✦</div><img className="mascot-image" src={`${BASE}/mascot-cat.png`} alt=""/><div className="mascot-caption">มาเรียนด้วยกันนะ!</div></div> }

function Field({label, type='text', value, onChange, placeholder, icon:Icon, error, onFocus}){ const [show,setShow]=useState(false); const isPassword=type==='password'; return <label className="field"><span>{label}</span><div className={`input-wrap ${error?'has-error':''}`}><Icon size={18}/><input type={isPassword && !show ? 'password':'text'} value={value} onChange={onChange} onFocus={onFocus} placeholder={placeholder} autoComplete={isPassword?'current-password':'email'}/>{isPassword && <button type="button" className="icon-button" aria-label={show?'ซ่อนรหัสผ่าน':'แสดงรหัสผ่าน'} onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button>}</div>{error && <small className="field-error"><AlertCircle size={14}/>{error}</small>}</label> }

function Login({session, go}){
 const [email,setEmail]=useState(''), [password,setPassword]=useState(''), [busy,setBusy]=useState(false), [googleBusy,setGoogleBusy]=useState(false), [error,setError]=useState(''), [focused,setFocused]=useState(false)
 useEffect(()=>{ if(session) go('/home') },[session])
 const submit=async(e)=>{e.preventDefault();setError(''); if(!email.trim()) return setError('กรุณากรอกอีเมล'); if(!isValidEmail(email)) return setError('รูปแบบอีเมลไม่ถูกต้อง'); if(!password) return setError('กรุณากรอกรหัสผ่าน'); if(!isSupabaseConfigured) return setError('ยังไม่ได้ตั้งค่าระบบเข้าสู่ระบบ'); setBusy(true); const {error}=await supabase.auth.signInWithPassword({email:email.trim(),password}); setBusy(false); if(error) setError(thaiError(error.message)); }
 const google=async()=>{setError(''); if(!isSupabaseConfigured) return setError('ยังไม่ได้ตั้งค่าระบบเข้าสู่ระบบ'); setGoogleBusy(true); const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:`${window.location.origin}${BASE}/home`}}); if(error){setGoogleBusy(false);setError(thaiError(error.message))} }
 return <main className="page"><div className="ambient a1"></div><div className="ambient a2"></div><header><Logo/><div className="help">มีบัญชีแล้วใช่ไหม? <button onClick={()=>go('/register')}>สมัครสมาชิก</button></div></header><section className="auth-layout"><div className="welcome"><div className="eyebrow"><span></span> ห้องเรียนของคุณพร้อมแล้ว</div><h1>ยินดีต้อนรับ<br/><em>กลับมา!</em></h1><p>เปิดประตูสู่ภาษาใหม่ไปด้วยกัน<br/>วันละนิด ก็เก่งขึ้นได้ทุกวัน</p><Mascot/></div><div className="card"><div className="card-top"><h2>เข้าสู่ระบบ</h2><p>เข้ามาเรียนรู้ต่อจากครั้งที่แล้วกันเถอะ</p></div><form onSubmit={submit} noValidate><Field label="อีเมล" value={email} onChange={e=>{setEmail(e.target.value);setError('')}} placeholder="ใส่อีเมลของคุณ" icon={Mail} onFocus={()=>setFocused(true)}/><Field label="รหัสผ่าน" type="password" value={password} onChange={e=>{setPassword(e.target.value);setError('')}} placeholder="ใส่รหัสผ่านของคุณ" icon={LockKeyhole} onFocus={()=>setFocused(true)}/>{error && <div className="alert"><AlertCircle size={17}/><span>{error}</span></div>}<div className="forgot"><button type="button" onClick={()=>go('/reset')}>ลืมรหัสผ่าน?</button></div><button className="primary" disabled={busy||googleBusy}>{busy?<><LoaderCircle className="spin" size={19}/>กำลังเข้าสู่ระบบ...</>:<>เข้าสู่ระบบ<ArrowRight size={19}/></>}</button></form><div className="divider"><span>หรือ</span></div><button className="google" onClick={google} disabled={busy||googleBusy}><span className="google-g">G</span>{googleBusy?<><LoaderCircle className="spin" size={18}/>กำลังเชื่อมต่อ...</>:'เข้าสู่ระบบด้วย Google'}</button><p className="card-foot">ยังไม่มีบัญชี? <button onClick={()=>go('/register')}>สมัครสมาชิก</button></p></div></section><footer>© 2026 เรียนภาษา <span>•</span> เรียนสนุกไปด้วยกัน</footer></main>
}

function SimplePage({type,go}){ const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false); const reset=async e=>{e.preventDefault();setError('');if(!email.trim()) return setError('กรุณากรอกอีเมล');if(!isValidEmail(email))return setError('รูปแบบอีเมลไม่ถูกต้อง');if(!isSupabaseConfigured)return setError('ยังไม่ได้ตั้งค่าระบบเข้าสู่ระบบ');setBusy(true);const {error}=await supabase.auth.resetPasswordForEmail(email.trim(),{redirectTo:`${window.location.origin}${BASE}/reset`});setBusy(false);if(error)setError(thaiError(error.message));else setMessage('ส่งลิงก์สำหรับตั้งรหัสผ่านใหม่ไปที่อีเมลของคุณแล้ว')}; const register=async e=>{e.preventDefault();setError('');if(!email.trim())return setError('กรุณากรอกอีเมล');if(!isValidEmail(email))return setError('รูปแบบอีเมลไม่ถูกต้อง');if(!password||password.length<6)return setError('รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร');if(!isSupabaseConfigured)return setError('ยังไม่ได้ตั้งค่าระบบเข้าสู่ระบบ');setBusy(true);const {error}=await supabase.auth.signUp({email:email.trim(),password});setBusy(false);if(error)setError(thaiError(error.message));else setMessage('สมัครสมาชิกสำเร็จ คุณสามารถเริ่มใช้งานได้ทันที')}; return <main className="simple"><div className="simple-card"><Logo/>{type==='reset'?<><h1>ลืมรหัสผ่าน?</h1><p>ไม่เป็นไรนะ เราจะส่งลิงก์สำหรับตั้งรหัสผ่านใหม่ให้คุณ</p><form onSubmit={reset}><Field label="อีเมล" value={email} onChange={e=>{setEmail(e.target.value);setError('')}} placeholder="ใส่อีเมลของคุณ" icon={Mail}/>{error&&<div className="alert"><AlertCircle size={17}/>{error}</div>}{message&&<div className="success"><CheckCircle2 size={17}/>{message}</div>}<button className="primary" disabled={busy}>{busy?<><LoaderCircle className="spin" size={19}/>กำลังส่ง...</>:'ส่งลิงก์ตั้งรหัสผ่าน'}</button></form></>:<><h1>สมัครสมาชิก</h1><p>สร้างบัญชีใหม่ แล้วเริ่มเรียนรู้ไปด้วยกัน</p><form onSubmit={register}><Field label="อีเมล" value={email} onChange={e=>{setEmail(e.target.value);setError('')}} placeholder="ใส่อีเมลของคุณ" icon={Mail}/><Field label="รหัสผ่าน" type="password" value={password} onChange={e=>{setPassword(e.target.value);setError('')}} placeholder="อย่างน้อย 6 ตัวอักษร" icon={LockKeyhole}/>{error&&<div className="alert"><AlertCircle size={17}/>{error}</div>}{message&&<div className="success"><CheckCircle2 size={17}/>{message}</div>}<button className="primary" disabled={busy}>{busy?<><LoaderCircle className="spin" size={19}/>กำลังสมัครสมาชิก...</>:'สมัครสมาชิก'}</button></form></>}<button className="back" onClick={()=>go('/login')}>← กลับหน้าเข้าสู่ระบบ</button></div></main> }
function Home({session,go}){const logout=async()=>{localStorage.removeItem('englishAuthUser');await supabase.auth.signOut();go('/login')};useEffect(()=>{const user=session?.user;if(!user)return;localStorage.setItem('englishAuthUser',JSON.stringify({id:user.id,email:user.email,created_at:user.created_at,user_metadata:user.user_metadata||{}}));const onMessage=e=>{if(e.origin===window.location.origin&&e.data?.type==='english-logout')logout()};window.addEventListener('message',onMessage);return()=>window.removeEventListener('message',onMessage)},[session]);return <iframe title="Lumi English learning app" src={`${BASE}/learning/index.html`} style={{display:'block',width:'100%',height:'100dvh',border:0}}/>}
function App(){const [path,setPath]=useState(window.location.pathname.replace(BASE,'')||'/'),[session,setSession]=useState(null);const go=p=>{window.history.pushState({},'',p);setPath(p)};useEffect(()=>{window.onpopstate=()=>setPath(window.location.pathname.replace(BASE,'')||'/'); if(supabase){supabase.auth.getSession().then(({data})=>setSession(data.session));const {data}=supabase.auth.onAuthStateChange((_e,s)=>{if(!s)localStorage.removeItem('englishAuthUser');setSession(s)});return()=>data.subscription.unsubscribe()}},[]);if(path==='/home'&&!session)return <Login go={go}/>;if(path==='/home')return <Home session={session} go={go}/>;if(path==='/reset')return <SimplePage type="reset" go={go}/>;if(path==='/register')return <SimplePage type="register" go={go}/>;return <Login session={session} go={go}/>}

createRoot(document.getElementById('root')).render(<App/>)
